name: simple
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  cloud_firestore: ^6.0.0
  cupertino_icons: ^1.0.8
  firebase_core: ^4.4.0
  flutter:
    sdk: flutter
  # Import and use GeoFlutterFire2 package (advance/geoflutterfire2.dart only) just for smooth comparison.
  # No need to import it when you develop your app.
  # geoflutterfire2: ^2.3.15
  geoflutterfire_plus:
    path: ../
  google_maps_flutter: ^2.12.3
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
