name: geoflutterfire_plus
description: geoflutterfire_plus enables your flutter app to store and query cloud firestore documents based on their geographic location.
version: 0.0.10
homepage: https://github.com/KosukeSaigusa/geoflutterfire_plus

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=2.10.0'

dependencies:
  cloud_firestore: ^4.5.3
  flutter:
    sdk: flutter
  rxdart: ^0.27.7

dev_dependencies:
  build_runner: ^2.3.3
  cloud_firestore_platform_interface: ^5.12.1
  fake_cloud_firestore: ^2.4.1+1
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0
